baseURL = "https://sebastiandedeyne.com"
languageCode = "en-us"
title = "Sebastian De Deyne"

summaryLength = 1_000_000
rssLimit = 10
enableGitInfo = true

[taxonomies]
  category = "categories"

[permalinks]
  posts = "/:slug"
  categories = "/:title"

[author]
  name = "Sebastian De Deyne"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
      unsafe = true

